config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index] do
    resources :highlights, only: [:index, :update, :create]
   end
  resources :pages

  root 'pages#index'

end

app/models/highlight.rb
class Highlight < ActiveRecord::Base
    belongs_to :user
    belongs_to :page
end

app/models/page.rb
class Page < ActiveRecord::Base
	def hello_world(name)
		p "Hello World, I am #{name}"
	end
end

app/models/user.rb
class User < ActiveRecord::Base
    validates :name,  :presence => true
    has_many :highlights
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/highlights_controller.rb
class HighlightsController < ApplicationController
  # GET /highlights
  # GET /highlights.json
  def index
    @highlights = Highlight.where(user_id: params[:user_id])
  end


  # PATCH/PUT /highlights/1
  # PATCH/PUT /highlights/1.json
  def update
    # incipient debuggin lines:
    # p params
    # p request.body.read

    @highlight = Highlight.where(user_id: params[:user_id], page_id: params[:id]).first_or_create

    respond_to do |format|
      if @highlight.update(hightlights: JSON.parse(request.body.read)["hightlights"])
        format.json { render :show, status: :ok }
      else
        format.json { render json: @highlight.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # TODO use strong parameters, instead of access request directly. And verify issues parsing for encoded HTML
    # Never trust parameters from the scary internet, only allow the white list through.
    def highlight_params
      params.fetch(:highlight, {})
      # params.require(:hl).permit(:hightlights)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
    @users = User.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InterviewApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_pack_tag 'application' %>
  <%= stylesheet_pack_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<header>
<!-- Fixed navbar -->
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a href="#" class="btn btn-default"><i class="fas fa-highlighter"></i> hightlighter</a>
      </li>
    </ul>
    <form class="form-inline mt-2 mt-md-0">
      <select id="select-user" class="custom-select">
        <option value="" selected>Choose a user</option>
        <%= options_for_select(@users.collect {|p| [ p.name, p.id ] }) %>
      </select>
    </form>
  </div>
</nav>
</header>

<!-- Begin page content -->
<main role="main" class="container">
  <% @pages.each do |page| %>
    <div class="page">
      <h2><%= page.name %></h2>

      <div id="<%= page.id %>" class="text-book">
        <%= page.content.html_safe %>
      </div>
    </div>
  <% end %>
</main>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>